general:
  setup_name: {{ setup_name }}
  figure_extension: "pdf"
  font_size: 8
  line_widths: [1]
  line_colors: [grey, r, b, pink, g]
  path_observations: "./observations"
  fault_file: "output/dyn-kinmod-fault.xdmf"
  projection: {{ projection }}
  misfit: "cross-correlation"
  #misfit: "min_shifted_normalized_rms"
  client: "iris"
  hypocenter:
      lon: {{ lon }}
      lat: {{ lat }}
      depth_in_km: {{ depth }}
      onset: {{ onset }}

synthetics:
  - type: "instaseis"
    name: "instaseis_1"
    db: "syngine://prem_a_2s"
    mode: "green_functions"
    source_files: [{{ source_files }}]

waveform_plots:
  - type: "p"
    synthetics: ["instaseis_1"]
    stations: [{{ stations }}]
    kind: "displacement"
    enabled: true
    t_before: 20.0
    t_after: {{ t_after_P_onset }}
    shift_match_correlation: true
    filter_tmin: 10.0
    filter_tmax: 200.0
    ncol_per_component: 2
    components:
      - Z

  - type: "sh"
    synthetics: ["instaseis_1"]
    stations: [{{ stations }}]
    kind: "displacement"
    enabled: true
    t_before: 20.0
    t_after: {{ t_after_SH_onset }}
    shift_match_correlation: true
    filter_tmin: 10.0
    filter_tmax: 200.0
    ncol_per_component: 2
    components:
      - T

  - type: "generic"
    enabled: true
    stations: [{{ stations }}]
    kind: "displacement"
    synthetics: ["instaseis_1"]
    t_before: 0.0
    t_after: 3000.0
    normalize: false
    shift_match_correlation: true
    filter_tmin: 100.0
    filter_tmax: 500.0
    ncol_per_component: 1
    components:
      - E
      - N
      - Z
