name: Build Docker Image for EASI

on:
  workflow_dispatch: # This allows for manual triggering
  pull_request:
    branches:
      - main
  push:
    branches:
      - main



permissions:
  contents: read
  packages: write
  actions: read
  id-token: write  # Add this if needed
  checks: write    # Add this if needed



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Cache Docker layers to speed up the build
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # Remove previous Docker image if it exists
      - name: Remove previous Docker image if it exists
        run: |
          docker rmi -f ghcr.io/thomas-ulrich/easi-image:latest || echo "No previous image found"
      # Build Docker image
      - name: Build Docker image for EASI
        run: |
          docker build -f Dockerfile.easi.seisscoped -t ghcr.io/thomas-ulrich/easi-image:latest .
      # Push Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/thomas-ulrich/easi-image:latest
