name: Python Tests + Coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Docker
        run: |
          docker pull ghcr.io/thomas-ulrich/easi-image:latest

      - name: Run tests inside Docker
        run: |
         docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            ghcr.io/thomas-ulrich/easi-image:latest \
            bash -c "pytest --cov=dynworkflow --cov=external --cov=. --cov-report=xml"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
